version: '2'
services:
  db_invites:
    image: mariadb
    ports:
      - "4005:3306"
    expose:
      - "4005"
    environment:
      MYSQL_USER: invites_user
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: invites_db
      MYSQL_HOST: db_invites
    volumes:
      - db_invites:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db_invites:db_invites
    environment:
      PMA_HOST: db_invites
      PMA_ARBITRARY: 1
      MYSQL_USER: invites_user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '5000:80'
    expose:
      - "5000"
  ms_invites:
    build: .
    ports:
      - '3005:80'
    expose:
      - "3005"
    depends_on:
      - db_invites
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "5001:1025"
      - "5002:8025"
volumes:
  db_invites:
    driver: "local"
